// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vohkprtylwmaeejvplfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvaGtwcnR5bHdtYWVlanZwbGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODM0MDgsImV4cCI6MjA2Mzc1OTQwOH0.a02tg7lvc7wyss10nJJZcnt4mMoOypcyaE57QZoDiFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);